version: "3.9"

services:

    database_brainny:
        image: postgres
        container_name: database_brainny
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=lucasoliveira
            - POSTGRES_PASSWORD=brainny123
            - POSTGRES_DB=nest_api
        volumes:
            - pgdata:/data/postgres

  
    api:
            build: .
            
            container_name: nest_api
            
            restart: always
            
            ports:
                - ${API_PORT}:${API_PORT}

            volumes: 
            - .:/usr/app
            links: 
            - database_brainny
            depends_on:
            - database_brainny               



volumes:
    pgdata:
        driver: local
